name: Bank Backend App Pipeline

on:
  push:
    branches:
      - main

jobs:
  Continuous_Integration_Build_and_Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Otuu02/group3-backend-app
          ref: main

      - name: Build Container Image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }} .

      - name: Log in to Docker Registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.REGISTRY_NAME }} --password-stdin

      - name: Push Image to Docker Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }}

      - name: Clean Up Local Docker Images
        run: docker rmi ${{ secrets.REGISTRY_NAME }}/bank-app-backend:${{ github.run_number }}

      - name: Clean Up Repository on Runner
        run: rm -rf ./*

  Continuous_Deployment_GCP_K8S:
    runs-on: ubuntu-latest
    needs: Continuous_Integration_Build_and_Push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Kubernetes Deployment File
        run: |
          echo "Updating Kubernetes deployment file..."
          sed -i "s+gtech2024/group3_bankapp:.*+gtech2024/group3_bankapp:${{ github.run_number }}+g" deployment/deploy.yaml
          cat deployment/deploy.yaml

      - name: Authenticate to GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Install Google Cloud SDK and Kubernetes Auth Plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin

      - name: Configure kubectl for GKE
        run: gcloud container clusters get-credentials dev-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Bank Backend to Kubernetes
        run: |
          echo "Deploying application to Kubernetes..."
          kubectl apply -f deployment
          sleep 30
          kubectl get pods